name: task_manager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  injectable: ^2.3.5
  intl: ^0.18.1

  flutter_localizations:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5
  geolocator: ^11.0.0
  rxdart: ^0.27.7
  geocoding: ^3.0.0
  dio: ^5.4.2+1
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.2

flutter:

  uses-material-design: true

  assets:
     - assets/
     - lib/l10n/intl_en.arb
