name: task_manager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  injectable: ^2.3.5
  injectable_generator: ^2.4.2
  intl: ^0.18.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
     - assets/
     - lib/l10n/intl_en.arb
